site_name: My Docs
site_url: https://howtosteps.github.io/mkdocs-python-docker-compose/site/
nav:
  - Home: index.md
  - About: about.md
  - Setup: setup.md
  - Create Dockerfile : create-dockerfile.md
  - Define Docker-Compose : docker-compose.md
  - Build your app : build-your-app.md
  - Run the app : run-your-app.md
theme: readthedocs