site_name: How to use Docker Compose
site_url: https://howtosteps.github.io/mkdocs-python-docker-compose/site/
nav:
  - Introduction: index.md
  - Setup: setup.md
  - Create Dockerfile : create-dockerfile.md
  - Define Docker-Compose : docker-compose.md
  - Build your app : build-your-app.md
  - Check your app : check-your-app.md
theme: readthedocs